spring:
  datasource:

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: LIZHONGJIE199608

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

##################### Spring Boot WEB start #####################
# Server HTTP port.
server:
  port: 8888
  tomcat:
    uri-encoding: utf-8

# 配置security的账号密码
security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123